In [1]:
import os
import sys

import csv
import urllib

import pandas_datareader.data as web
import pandas as pd
import numpy as np
import datetime
import matplotlib

import pymongo
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

from scipy import stats
import seaborn as sn
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import pearsonr,spearmanr,chi2, chi2_contingency
from calendar import day_abbr, month_abbr, mdays
import holidays

from fbprophet import Prophet

from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score

Importing plotly failed. Interactive plots will not work.


# Data Acquisition

American Airlines Group Inc (AAL)

## Option 1: Go to official website "Yahoo Finance", and download the data in form of .csv file

As markets were closed for holiday,data begin from 2017/04/03

In [2]:
def download_save_csv(url,filename):
    data_dir='./Dataset'
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)    
    file_path=data_dir+'/'+filename+'.csv'
    if not os.path.exists(file_path):
        print("Downloading", filename, "...")
        file_path, headers = urllib.request.urlretrieve(url,file_path)
        print("Finished")
    else:
        print( filename, "existed")    
    return file_path

In [3]:
stock_url = 'https://query1.finance.yahoo.com/v7/finance/download/AAL?period1=1491004800&period2=1619827200&interval=1d&events=history&includeAdjustedClose=true'
stock_Path=download_save_csv(stock_url,'stock')
stock=pd.read_csv(stock_Path,parse_dates=True) 

stock existed


 Acquire auxiliary data

In [4]:
COVID_url = "https://covid19.who.int/WHO-COVID-19-global-data.csv"
Cases_Path= download_save_csv(COVID_url,'cases')
Cases=pd.read_csv(Cases_Path,parse_dates=True)  
caseUS=Cases.loc[Cases["Country_code"] == "US"]

cases existed


In [5]:
Cases.shape[0]
Cases.dtypes

In [6]:
Precipitation_url = "https://www.ncdc.noaa.gov/cag/national/time-series/110-pcp-all-12-2017-2021.csv?base_prd=true&begbaseyear=2017&endbaseyear=2021"
Precip_Path = download_save_csv(Precipitation_url ,'Precip')
Precip=pd.read_csv(Precip_Path,skiprows=[0,1,2,3], parse_dates=True,infer_datetime_format=True,date_parser=True)


Precip existed


In [7]:
Precip.shape[0]
Precip.dtypes

## Option 2: Through "pandas_datareader" package directly access the data.

In [8]:
startDate=datetime.datetime(2017,4,1)
endDate=datetime.datetime(2021,5,31)
Stock =web.DataReader("AAL","yahoo",startDate,endDate)
Stock.to_csv('./Dataset/Stock.csv',index=True, header=True)

In [9]:
Stock.dtypes

High         float64
Low          float64
Open         float64
Close        float64
Volume       float64
Adj Close    float64
dtype: object

Acquire auxiliary data

In [10]:
startDate=datetime.datetime(2017,4,1)
endDate=datetime.datetime(2021,5,31)
Oil =web.DataReader("CL=F","yahoo",startDate,endDate)
Oil.to_csv('./Dataset/Oil.csv',index=True, header=True) 

In [11]:
startDate=datetime.datetime(2017,4,1)
endDate=datetime.datetime(2021,5,31)
NASDAQ =web.DataReader("^IXIC","yahoo",startDate,endDate)
NASDAQ.to_csv('./Dataset/NASDAQ.csv',index=True, header=True) 

| Price Data  | Acquire auxiliary data   |
| :----------: | :-----------------------: |
| American Airlines Group Inc. Stock Price | Crude Oil Price
|| NASDA Index|
|| New COVID cases in US |
|| Precipitation |

# Data Storage

Original dataset have been saved in local filefolder "Dataset".

Now, storing data online (in MongoDB)

In [12]:
def save_to_db(dataName,Name):
    if not dataName.count_documents({}, limit = 1):
        dataName.insert_many(Name.to_dict(orient='records'))
        print("Uploading ...")
    else:
        dataName.delete_many({})
        dataName.insert_many(Name.to_dict(orient='records'))
        print("Updating ...")

In [13]:
def retrieving_data(dataName):
    if dataName.count_documents({}, limit = 1):
        table = dataName.find()
        Data=pd.DataFrame.from_records(table)
        Data.drop('_id',axis = 1,inplace = True)
        return Data
    
    else:
        print("No such Data existed in Database")


In [14]:
client = pymongo.MongoClient("mongodb+srv://hcy:0523@cluster0.piobu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.Assign

In [15]:
StockPrices = db['StockPrices']
Infects = db['Infects']
Precip_db = db['Precip_db']
Oil_db = db['Oil_db']
NASDAQ_db = db['NASDAQ_db']

In [16]:
Stock.reset_index(inplace=True)
caseUS.reset_index(inplace=True)
Precip.reset_index(inplace=True)
Oil.reset_index(inplace=True)
NASDAQ.reset_index(inplace=True)

In [17]:
save_to_db(StockPrices,Stock)
save_to_db(Infects,caseUS)
save_to_db(Precip_db,Precip)
save_to_db(Oil_db,Oil)
save_to_db(NASDAQ_db,NASDAQ)

Updating ...
Updating ...
Updating ...
Updating ...
Updating ...


In [18]:
client.close() # Disconnect to MongoDB after finishing storage to relieve memory space

# Data Preprocessing

In [19]:
image_dir='./image/Data Preprocessing/'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)   

Call the dataset in MonGodb,and adjust the header and index in a tidy way.

In [20]:
Stock_data=retrieving_data(db.StockPrices)
Cases_data=retrieving_data(db.Infects)
Precip_data=retrieving_data(db.Precip_db)
Oil_data=retrieving_data(db.Oil_db)
NASDAQ_data=retrieving_data(db.NASDAQ_db)

Stock_data.rename(columns={'Close':'Stock_Price'},inplace=True)
Stock_data=Stock_data.loc[:,['Date','Stock_Price']]
Stock_data.set_index('Date',drop=True,inplace=True)

Oil_data.rename(columns={'Close':'Oil_Price'},inplace=True)
Oil_data=Oil_data.loc[:,['Date','Oil_Price']]
Oil_data.set_index('Date',drop=True,inplace=True)

NASDAQ_data.rename(columns={'Close':'NASDAQ_Index'},inplace=True)
NASDAQ_data=NASDAQ_data.loc[:,['Date','NASDAQ_Index']]
NASDAQ_data.set_index('Date',drop=True,inplace=True)

Precip_data.set_index('Date',inplace=True)
Precip_data.rename(columns={'Value':'Precipitation'},inplace=True)
Precip_data=Precip_data.loc[:,['Precipitation']]

Cases_data=Cases_data.loc[Cases_data["Date_reported"] < "2021-12-31"]
Cases_data=Cases_data.rename(columns={'Date_reported':'Date'})
Cases_data=Cases_data[['Date','New_cases']]
Cases_data.set_index('Date',drop=True,inplace=True)
Cases_data['New_cases']=True

In [116]:
Combine

Stock_Price  Oil_Price  NASDAQ_Index  Precipitation  New_cases
Date                                                                      
2017-04-03    42.450001  50.240002   5894.680176       3.490667      False
2017-04-04    40.900002  51.029999   5898.609863       3.486000      False
2017-04-05    41.310001  51.150002   5864.479980       3.481333      False
2017-04-06    41.720001  51.700001   5878.950195       3.476667      False
2017-04-07    41.810001  52.240002   5877.810059       3.472000      False
...                 ...        ...           ...            ...        ...
2021-05-24    22.990000  66.050003  13661.169922       2.982581       True
2021-05-25    23.209999  66.070000  13657.169922       2.982258       True
2021-05-26    23.900000  66.209999  13738.000000       2.981935       True
2021-05-27    24.430000  66.849998  13736.280273       2.981613       True
2021-05-28    24.240000  66.320000  13748.740234       2.981290       True

[1047 rows x 5 columns]

## Process outliers values

Compared with Z_score and IQR_score, Z_score is applied

Cap outliers

In [21]:
image_dir='./image/Data Preprocessing/outliers'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)   
    
def Z_score(Data,yTitle,filename):
    day=Data.reset_index()
    data=np.array(Data).reshape(1,len(day))[0]
    day=np.array(day.iloc[:,0])
    day=day.reshape(1,len(day))[0]
    z = np.abs(stats.zscore(data))
    threshold = 3
    loc = np.where(z > threshold)
    outlier = data[loc]
    print('the data classified as outlier by z score:\r\n', outlier)
    print('the year of the outlier is:\r\n',day[loc])

    drop = np.array([remain for remain in data if remain not in outlier])
    drop_day = np.array([remain for remain in day if remain not in day[loc]])
    cap=np.copy(data)
    print('Before cap the outlier, its value:\r\n',cap[loc])
    # cap the outliers
    Num=[]
    for i,element in enumerate(cap[loc]):
        print(i)
        if element>np.mean(drop):
            Num.append(np.max(drop))
            print(cap[loc][i])
        else:
            Num.append(np.min(drop))

    cap[loc]=Num
    print('After cap the outlier, its value:\r\n',cap[loc])
    Data.iloc[:,0]=cap 
    
    file_path=image_dir+'/'+filename+'.jpg'
    
    fig, (ax1, ax2) = plt.subplots(2, 1, sharey=True,sharex=True, figsize=(10, 16))
    ax1.set_title('Before Cap')
    ax1.scatter(day,data)
    ax1.scatter(day[loc], data[loc], c='r')
    ax1.set_xlabel('Date')
    ax1.set_ylabel(yTitle)
    ax1.grid(which='major',axis='y')

    ax2.set_title('After cap')
    ax2.scatter(day,cap)
    ax2.scatter(day[loc], cap[loc], c='r')
    ax2.set_xlabel('Date')
    ax2.set_ylabel(yTitle)
    ax2.grid(which='major',axis='y')
    plt.savefig(file_path)
    plt.close(fig)

def  IQR_score(outlier_dataset):
    outlier_dataset=np.array(outlier_dataset)
    Q1 = np.quantile(outlier_dataset,0.25)
    Q3 = np.quantile(outlier_dataset,0.75)
    IQR = Q3-Q1
    Minimum = Q1-1.5*IQR
    Maximum = Q3+1.5*IQR

    # find values that meets the conditions: (outlier_dataset<Minimum) or (outlier_dataset>Maximum)
    outlier_by_IQR_Score=outlier_dataset[(outlier_dataset<Minimum) | (outlier_dataset>Maximum)]
    print('The data classified as outlier by IQR score:\r\n', outlier_by_IQR_Score)
    

In [22]:
plt.boxplot(Stock_data)
plt.savefig('./image/Data Preprocessing/outliers/boxStock')
Z_score(Stock_data,"Price in USD","Stock")
plt.close()

the data classified as outlier by z score:
 []
the year of the outlier is:
 []
Before cap the outlier, its value:
 []
After cap the outlier, its value:
 []


Stock_data is clean data

In [23]:
plt.boxplot(Oil_data)
plt.savefig('./image/Data Preprocessing/outliers/boxOil')
Z_score(Oil_data,"prices in USD","Oil")
plt.close()

the data classified as outlier by z score:
 [ 18.27000046 -37.63000107  10.01000023  13.77999973  16.5
  16.94000053  12.77999973  12.34000015  15.06000042]
the year of the outlier is:
 ['2020-04-17T00:00:00.000000000' '2020-04-20T00:00:00.000000000'
 '2020-04-21T00:00:00.000000000' '2020-04-22T00:00:00.000000000'
 '2020-04-23T00:00:00.000000000' '2020-04-24T00:00:00.000000000'
 '2020-04-27T00:00:00.000000000' '2020-04-28T00:00:00.000000000'
 '2020-04-29T00:00:00.000000000']
Before cap the outlier, its value:
 [ 18.27000046 -37.63000107  10.01000023  13.77999973  16.5
  16.94000053  12.77999973  12.34000015  15.06000042]
0
1
2
3
4
5
6
7
8
After cap the outlier, its value:
 [18.84000015 18.84000015 18.84000015 18.84000015 18.84000015 18.84000015
 18.84000015 18.84000015 18.84000015]


In [24]:
plt.boxplot(NASDAQ_data)
plt.savefig('./image/Data Preprocessing/outliers/boxNASDAQ')
Z_score(NASDAQ_data,"prices in USD",'NASDAQ')
plt.close()

the data classified as outlier by z score:
 []
the year of the outlier is:
 []
Before cap the outlier, its value:
 []
After cap the outlier, its value:
 []


In [25]:
plt.boxplot(Precip_data)
plt.savefig('./image/Data Preprocessing/outliers/boxPrecip')
Z_score(Precip_data,"inch",'Precipiation')
plt.close()

the data classified as outlier by z score:
 [4.47]
the year of the outlier is:
 [201905]
Before cap the outlier, its value:
 [4.47]
0
4.47
After cap the outlier, its value:
 [3.57]


## Process missing values

In [26]:
image_dir='./image/Data Preprocessing/missing'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)  

Precipitation varys according to seasons. Through resample of monthly Precipitationin to get the daily Precipitationin

In [27]:
def Resample(df):
    # Upsample in order to have data for every day.
    df_RE = df.resample('1D')

    # Interpolate through time
    df_RE = df_RE.interpolate(method='time')


    return df_RE

In [28]:
Precip_data.reset_index(inplace=True)
Precip_data['Date']=[datetime.datetime.strptime(str(time),'%Y%m') for time in Precip_data['Date']]
Precip_data.set_index('Date',inplace=True,drop=True)
Precip_data=Resample(Precip_data)

In [29]:
Cases_data.reset_index(inplace=True)
Cases_data.set_index('Date',inplace=True,drop=True)
Cases_data.index=pd.DatetimeIndex(Cases_data.index)

In [30]:
Combine = pd.concat([Stock_data,Oil_data,NASDAQ_data,Precip_data,Cases_data],axis=1)

There will be no change in the markets closing period because there will be no trading and the share price will not change.

In [31]:
Combine.dropna(axis=0,subset = ['Stock_Price'],inplace=True)

In [32]:
Combine.isnull().sum() 

Stock_Price        0
Oil_Price          0
NASDAQ_Index       0
Precipitation      0
New_cases        693
dtype: int64

For New Cases of COVID in US, there is no influence before the pandemic, so the missing data before that day finding the first case is False.

In [33]:
Combine['New_cases'].fillna(False,inplace=True)

Determine if there are still missing data

In [126]:
print('Wheher the missing value exists:')
Combine.isnull().any()

Test missing value exists:


Stock_Price      False
Oil_Price        False
NASDAQ_Index     False
Precipitation    False
New_cases        False
dtype: bool

Now, there is no missing data

In [35]:
Combine.to_csv('./Dataset/Combine.csv', index=True, header=True)

In [36]:
print(Combine.columns)
print(Combine.index)

Index(['Stock_Price', 'Oil_Price', 'NASDAQ_Index', 'Precipitation',
       'New_cases'],
      dtype='object')
DatetimeIndex(['2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
               '2017-04-07', '2017-04-10', '2017-04-11', '2017-04-12',
               '2017-04-13', '2017-04-17',
               ...
               '2021-05-17', '2021-05-18', '2021-05-19', '2021-05-20',
               '2021-05-21', '2021-05-24', '2021-05-25', '2021-05-26',
               '2021-05-27', '2021-05-28'],
              dtype='datetime64[ns]', name='Date', length=1047, freq=None)


In [37]:
Y = Combine.loc[:,'Stock_Price']
Y1 = Combine.loc[:,'Oil_Price']
Y2 = Combine.loc[:,'NASDAQ_Index']
Y3 = Combine.loc[:,'New_cases']
Y4 = Combine.loc[:,'Precipitation']

In [38]:
fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, sharey=True, figsize=(14, 14))
ax1.hist(Y)
ax1.set_ylabel('Stock_Price Count')
ax2.hist(Y1)
ax2.set_ylabel('Oil_Price Count')
ax3.hist(Y2)
ax3.set_ylabel('NASDAQ_Index Count')
ax4.hist(Y4)
ax4.set_ylabel('Precipitation Count')
plt.savefig('./image/Data Preprocessing/missing/hist')
plt.close()

In [39]:
fig, (ax1, ax2, ax3, ax4, ax5) =plt.subplots(5, sharex=True,figsize=(10, 16))
ax1.plot(Y,label='Stock_Price', c='r')
ax1.set_ylabel('Stock Price in USD')
ax1.grid()
ax1.legend()

ax2.plot(Y1,label='Oil_Price', c='b')
ax2.set_ylabel('Oil Price in USD')
ax2.grid()
ax2.legend()

ax3.plot(Y2,label='NASDAQ_Index', c='y')
ax3.set_ylabel('NASDAQ Index')
ax3.grid( )
ax3.legend()

ax4.plot(Y3,label='New_cases', c='g')
ax4.set_ylabel('New COVID cases in US')
ax4.grid()
ax4.legend()

ax5.plot(Y4,label='Precipitation', c='black')
ax5.set_xlabel('Date')
ax5.set_ylabel('Precipitation in Inches')
ax5.grid()
ax5.legend()

plt.savefig('./image/Data Preprocessing/missing/plot')
plt.close()

# label='Stock_Price'
# label='Oil_Price'
# label='NASDAQ_Index'
# label='New_cases'
# label='Precipitation'

Data Normalization

In [40]:
Precip_data['Precipitation']=Combine['Precipitation']

In [41]:
Precip_data.dropna(axis=0,inplace=True)

In [42]:
Combine_fit=Combine.copy()

scaler0 = MinMaxScaler()
Stock_fit=Stock_data.copy()
Stock_fit['Stock_Price']=scaler0.fit_transform(Stock_data)

scaler1 = MinMaxScaler()
Oil_fit=Oil_data.copy()
Oil_fit['Oil_Price']=scaler1.fit_transform(Oil_data)

scaler2 = MinMaxScaler()
NASDAQ_fit=NASDAQ_data.copy()
NASDAQ_fit['NASDAQ_Index']=scaler2.fit_transform(NASDAQ_data)

scaler3 = MinMaxScaler()
Precip_fit=Precip_data.copy()
Precip_fit['Precipitation']=scaler3.fit_transform(Precip_data)


In [43]:
X = Combine_fit['Stock_Price']
X1 = Combine_fit['Oil_Price']
X2 = Combine_fit['NASDAQ_Index']
X4 = Combine_fit['Precipitation']

In [44]:
Combine_fit=Combine.copy()

scaler = MinMaxScaler()

Combine_fit=scaler.fit_transform(Combine)
Combine_fit=pd.DataFrame(Combine_fit,index=Combine.index,columns=Combine.columns)

In [45]:
Combine_fit.boxplot()
plt.savefig('./image/Data Preprocessing/missing/box_fit')
plt.close()

# Data Exploration

In [46]:
image_dir='./image/Data Exploration'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)

Quantitative attributes:stock price (USD), precipitation(Inch), NASDAQ Index (USD), Crude Oil (USD), Cases of COVID in US (persons).


Fuction df.describe() provide minimum, mean,maximum, standard deviation of each data

In [47]:
Des=Combine.describe()
Des.to_csv('./Dataset/Combine_describe.csv',index=True, header=True) 

 Explore seasonal cycles

In [48]:
def seasonal_cycle(Dataset,title):
    seasonal_cycle = Dataset.rolling(window=30, center=True).mean().groupby(Dataset.index.dayofyear).mean()
    q25 = Dataset.rolling(window=30, center=True).mean().groupby(Dataset.index.dayofyear).quantile(0.25)
    q75 = Dataset.rolling(window=30, center=True).mean().groupby(Dataset.index.dayofyear).quantile(0.75)
    Day_in_Mon = mdays.copy()
    Day_in_Mon[2] = 29
    Day_in_Mon = np.cumsum(Day_in_Mon)
    month_ticks = month_abbr[1:]
    Fre, axes = plt.subplots(figsize=(10,7)) 

    seasonal_cycle.plot(ax=axes, lw=2, color='b', legend=False)
    axes.fill_between(seasonal_cycle.index, q25.values.ravel(), q75.values.ravel(), color='b', alpha=0.3)
    axes.set_xticklabels(month_ticks)
    axes.grid(ls=':')
    axes.set_xlabel('Month', fontsize=15)
    axes.set_ylabel(title, fontsize=15);
    axes.set_xlim(0, 365)
    [l.set_fontsize(13) for l in axes.xaxis.get_ticklabels()]
    [l.set_fontsize(13) for l in axes.yaxis.get_ticklabels()]

    axes.set_title('30 days running average '+title, fontsize=15)
    plt.savefig('./image/Data Exploration/seasonal_cycle '+title)
    plt.close()


In [49]:
seasonal_cycle(Stock_data,'Price of stock')
seasonal_cycle(Oil_data,'Price of Oil')
seasonal_cycle(NASDAQ_data,'NASDAQ Index')
seasonal_cycle(Precip_data,'Precipitation')

Explore dependency on year and month

In [50]:
def year_and_month(Dataset,title):
    month_year = Dataset.copy()
    month_year.loc[:,'year'] = month_year.index.year
    month_year.loc[:,'month'] = month_year.index.month
    month_year = month_year.groupby(['year','month']).mean().unstack()
    month_year.columns = month_year.columns.droplevel(0)

    f, ax = plt.subplots(figsize=(12,6))

    sn.heatmap(month_year, ax=ax, cmap=plt.cm.viridis, cbar_kws={'boundaries':np.arange(10000,45000,5000)})

    cbax = f.axes[1]
    [l.set_fontsize(13) for l in cbax.yaxis.get_ticklabels()]
    cbax.set_ylabel(title, fontsize=13)

    [ax.axhline(x, ls=':', lw=0.5, color='0.8') for x in np.arange(1, 7)]
    [ax.axvline(x, ls=':', lw=0.5, color='0.8') for x in np.arange(1, 24)];

    ax.set_title(title+' per year and month', fontsize=16)

    [l.set_fontsize(13) for l in ax.xaxis.get_ticklabels()]
    [l.set_fontsize(13) for l in ax.yaxis.get_ticklabels()]

    ax.set_xlabel('Month', fontsize=15)
    ax.set_ylabel('Year', fontsize=15)
    ax.set_yticklabels(np.arange(2017, 2022, 1), rotation=0);
    plt.savefig('./image/Data Exploration/year_and_month '+title)
    plt.close()

In [51]:
year_and_month(Stock_data,'Price of stock')
year_and_month(Oil_data,'Price of Oil')
year_and_month(NASDAQ_data,'NASDAQ Index')
year_and_month(Precip_data,'Precipitation')

Explore dependency on day of the week and month

In [52]:
def month_day(Dataset,title):
    month_day = Dataset.copy()
    month_day.loc[:,'day_of_week'] = month_day.index.dayofweek
    month_day.loc[:,'month'] = month_day.index.month
    month_day = month_day.groupby(['day_of_week','month']).mean().unstack()
    month_day.columns = month_day.columns.droplevel(0)

    f, ax = plt.subplots(figsize=(12,6))

    sn.heatmap(month_day, ax = ax, cmap=plt.cm.viridis, cbar_kws={'boundaries':np.arange(10000,45000,5000)})

    cbax = f.axes[1]
    [l.set_fontsize(13) for l in cbax.yaxis.get_ticklabels()]
    cbax.set_ylabel('Santander cycles hires', fontsize=13)

    [ax.axhline(x, ls=':', lw=0.5, color='0.8') for x in np.arange(1, 7)]
    [ax.axvline(x, ls=':', lw=0.5, color='0.8') for x in np.arange(1, 24)];

    ax.set_title(title+' per day of the week and month', fontsize=16)

    [l.set_fontsize(13) for l in ax.xaxis.get_ticklabels()]
    [l.set_fontsize(13) for l in ax.yaxis.get_ticklabels()]

    ax.set_xlabel('Month', fontsize=15)
    ax.set_ylabel('Day of the week', fontsize=15)
    ax.set_yticklabels(day_abbr[0:month_day.shape[0]]);
    plt.savefig('./image/Data Exploration/month_day '+title)
    plt.close()

In [53]:
month_day(Stock_data,'Price of stock')
month_day(Oil_data,'Price of Oil')
month_day(NASDAQ_data,'NASDAQ Index')
month_day(Precip_data,'Precipitation')

Explore weekdays and weekends trends
As markets close in the weekend, it is make no sense to find weekends trends.

Explore holidays trends

In [54]:
holidays_df = pd.DataFrame([], columns = ['ds','holiday'])
ldates = []
lnames = []
for date, name in sorted(holidays.UnitedStates(years=np.arange(2017, 2021 + 1)).items()):
    ldates.append(date)
    lnames.append(name)
    
ldates = np.array(ldates)
lnames = np.array(lnames)
holidays_df.loc[:,'ds'] = ldates
holidays_df.loc[:,'holiday'] = lnames
holidays_df.holiday.unique()
holidays_df.loc[:,'holiday'] = holidays_df.loc[:,'holiday'].apply(lambda x : x.replace(' (Observed)',''))

In [120]:
holidays_df

ds                               holiday
0  2017-01-01                        New Year's Day
1  2017-01-02                        New Year's Day
2  2017-01-16            Martin Luther King Jr. Day
3  2017-02-20                 Washington's Birthday
4  2017-05-29                          Memorial Day
5  2017-07-04                      Independence Day
6  2017-09-04                             Labor Day
7  2017-10-09                          Columbus Day
8  2017-11-10                          Veterans Day
9  2017-11-11                          Veterans Day
10 2017-11-23                          Thanksgiving
11 2017-12-25                         Christmas Day
12 2018-01-01                        New Year's Day
13 2018-01-15            Martin Luther King Jr. Day
14 2018-02-19                 Washington's Birthday
15 2018-05-28                          Memorial Day
16 2018-07-04                      Independence Day
17 2018-09-03                             Labor Day
18 2018-10-08                          Columbus Day
19 2018-11-11                          Veterans Day
20 2018-11-12                          Veterans Day
21 2018-11-22                          Thanksgiving
22 2018-12-25                         Christmas Day
23 2019-01-01                        New Year's Day
24 2019-01-21            Martin Luther King Jr. Day
25 2019-02-18                 Washington's Birthday
26 2019-05-27                          Memorial Day
27 2019-07-04                      Independence Day
28 2019-09-02                             Labor Day
29 2019-10-14                          Columbus Day
30 2019-11-11                          Veterans Day
31 2019-11-28                          Thanksgiving
32 2019-12-25                         Christmas Day
33 2020-01-01                        New Year's Day
34 2020-01-20            Martin Luther King Jr. Day
35 2020-02-17                 Washington's Birthday
36 2020-05-25                          Memorial Day
37 2020-07-03                      Independence Day
38 2020-07-04                      Independence Day
39 2020-09-07                             Labor Day
40 2020-10-12                          Columbus Day
41 2020-11-11                          Veterans Day
42 2020-11-26                          Thanksgiving
43 2020-12-25                         Christmas Day
44 2021-01-01                        New Year's Day
45 2021-01-18            Martin Luther King Jr. Day
46 2021-02-15                 Washington's Birthday
47 2021-05-31                          Memorial Day
48 2021-06-18              Confederate Memorial Day
49 2021-06-19  Juneteenth National Independence Day
50 2021-07-04                      Independence Day
51 2021-07-05                      Independence Day
52 2021-09-06                             Labor Day
53 2021-10-11                          Columbus Day
54 2021-11-11                          Veterans Day
55 2021-11-25                          Thanksgiving
56 2021-12-24                         Christmas Day
57 2021-12-25                         Christmas Day
58 2021-12-31                        New Year's Day

In [118]:
Dataset = Stock_data.copy()
holidays = Dataset.loc[Dataset.index.isin(holidays_df['ds'])]
normaldays = Dataset.loc[~Dataset.index.isin(holidays_df['ds'])]
summary_month_holidays = holidays.groupby(holidays.index.month).describe()
summary_month_holidays.columns = summary_month_holidays.columns.droplevel(0)
summary_month_holidays["mean"]

Date
10    31.7600
11    31.3275
Name: mean, dtype: float64

In [129]:
print('Holidays that stock markets opening: ')
holidays

Holidays that stock markets opening: 


Stock_Price
Date                   
2017-10-09    50.599998
2017-11-10    45.820000
2018-10-08    35.900002
2018-11-12    36.860001
2019-10-14    27.620001
2019-11-11    30.590000
2020-10-12    12.920000
2020-11-11    12.040000

In [57]:
def holidays(Dataset,title):
    Dataset = Dataset.copy()
    holidays = Dataset.loc[Dataset.index.isin(holidays_df['ds'])]
    normaldays = Dataset.loc[~Dataset.index.isin(holidays_df['ds'])]
    summary_month_holidays = holidays.groupby(holidays.index.month).describe()
    summary_month_normaldays = normaldays.groupby(normaldays.index.month).describe()
    summary_month_holidays.columns = summary_month_holidays.columns.droplevel(0)
    summary_month_normaldays.columns = summary_month_normaldays.columns.droplevel(0)
    f, ax = plt.subplots(figsize=(10,7))

    ax.plot(summary_month_holidays.index, summary_month_holidays.loc[:,'mean'], color='y', label='Holidays', ls='--', lw=3)
    ax.fill_between(summary_month_holidays.index, summary_month_holidays.loc[:,'25%'], \
                    summary_month_holidays.loc[:,'75%'], facecolor='y', alpha=0.1)
    ax.plot(summary_month_normaldays.index, summary_month_normaldays.loc[:,'mean'], color='b', label='Weekdays', lw=3)
    ax.fill_between(summary_month_normaldays.index, summary_month_normaldays.loc[:,'25%'], \
                    summary_month_normaldays.loc[:,'75%'], facecolor='b', alpha=0.1)
    ax.legend(fontsize=15)
    ax.set_xticks(range(1,13));
    ax.grid(ls=':', color='0.8')
    ax.set_xlabel('Month', fontsize=15)
    ax.set_ylabel(title, fontsize=15);

    [l.set_fontsize(13) for l in ax.xaxis.get_ticklabels()]
    [l.set_fontsize(13) for l in ax.yaxis.get_ticklabels()]

    plt.savefig('./image/Data Exploration/holidays '+title)
    plt.close()

In [58]:
holidays(Stock_data,'Price of stock')
holidays(Oil_data,'Price of Oil')
holidays(NASDAQ_data,'NASDAQ Index')
holidays(Precip_data,'Precipitation')

### Data Relationships

In [59]:
image_dir='./image/Data Exploration/Data Relationships'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)

In [60]:
def DEmean(x):
    x_mean = np.mean(x)
    return [i - x_mean for i in x]

def covariance(x, y):
    n = len(x)
    return np.dot(DEmean(x), DEmean(y)) / (n-1)

#### Stock Price 

Variance

In [61]:
var0=np.var(Y)

#### Stock Price  VS Curde Oil Price 

Covariance

In [62]:
cov1=covariance(Y, Y1)
Cov1=np.cov(Y, Y1)

In [63]:
sn.heatmap(Cov1, annot=True, fmt='g')
plt.savefig('./image/Data Exploration/Data Relationships/Stock Oil')
plt.close()

Variance of Curde Oil Price 

In [64]:
var1=np.var(Y1)

Correlation

In [65]:
np.cov(X, X1)

array([[181.88419941,  80.45081336],
       [ 80.45081336, 129.98519242]])

In [66]:
corr1, _ = pearsonr(Y, Y1)
print("pearsonr correlation is", corr1)

pearsonr correlation is 0.523222018733247


In [67]:
Corr1, _ = spearmanr(Y, Y1)
print("spearmanr correlation", Corr1)

spearmanr correlation 0.44995621655522566


In [68]:
plt.scatter(Y, Y1)
plt.title('Stock Price  VS Curde Oil Price ')
plt.ylabel('Curde Oil Price ($USD$)')
plt.xlabel('Stock Price ($USD$)')
plt.savefig('./image/Data Exploration/Data Relationships/Stock Oil scatter')
plt.close()

#### Stock Price  VS NASDAQ_Index

Covariance

In [69]:
cov2=covariance(Y, Y2)
Cov2=np.cov(Y, Y2)

In [70]:
sn.heatmap(Cov2, annot=True, fmt='g')
plt.savefig('./image/Data Exploration/Data Relationships/Stock NASDAQ')
plt.close()

Variance of NASDAQ_Index

In [71]:
var2=np.var(Y2)

Correlation

In [72]:
np.cov(X, X2)

array([[ 1.81884199e+02, -2.16447811e+04],
       [-2.16447811e+04,  4.90746607e+06]])

In [73]:
corr2, _ = pearsonr(Y, Y2)
print("pearsonr correlation is", corr2)

pearsonr correlation is -0.7244810967823465


In [74]:
Corr2, _ = spearmanr(Y, Y2)
print("spearmanr correlation", Corr2)

spearmanr correlation -0.8122049725128923


In [75]:
plt.scatter(Y, Y2)
plt.title('Stock Price  VS NASDAQ_Index ')
plt.ylabel('NASDAQ_Index ($USD$)')
plt.xlabel('Stock Price ($USD$)')
plt.savefig('./image/Data Exploration/Data Relationships/Stock NASDAQ scatter')
plt.close()

#### Stock Price  VS Precipitation 

Covariance

In [76]:
cov4=covariance(Y, Y4)
Cov4=np.cov(Y, Y4)

In [77]:
sn.heatmap(Cov4, annot=True, fmt='g')
plt.savefig('./image/Data Exploration/Data Relationships/Stock Precipitation')
plt.close()

Variance of  Precipitation

In [78]:
var4=np.var(Y4)

Correlation

In [79]:
np.cov(X, X4)

array([[181.88419941,   1.06429809],
       [  1.06429809,   0.20976728]])

In [80]:
corr4, _ = pearsonr(Y, Y4)
print("pearsonr correlation is", corr4)

pearsonr correlation is 0.1723046214674639


In [81]:
Corr4, _ = spearmanr(Y, Y4)
print("spearmanr correlation", Corr4)

spearmanr correlation 0.2228940247709982


In [82]:
plt.scatter(Y, Y4)
plt.title('Stock Price  VS Precipitation ')
plt.ylabel('Precipitation ($Inch$)')
plt.xlabel('Stock Price ($USD$)')
plt.savefig('./image/Data Exploration/Data Relationships/Stock Precipitation scatter')
plt.close()

Elements influencing Stock Price of American Airlines Group Inc.:

|    | Positive  | negative   |
| :----------: | :-----------------------: |:-----------------------: |
|  High Degree |Oil_Price  |NASDAQ_Index | 
|  low Degree  |Precipitation | New_cases|

In [131]:
columns=['Oil_Price', 'NASDAQ_Index','Precipitation']
Oil_Price=[var1,cov1,corr1,Corr1]
NASDAQ_Index=[var2,cov2,corr2,Corr2]
Precipitation=[var4,cov4,corr4,Corr4]
index=['Variance','Covariance','Pearsonr_correlation','Spearmanr_correlation']

dic={'Oil_Price':Oil_Price, 'NASDAQ_Index':NASDAQ_Index, 
      'Precipitation':Precipitation}

df=pd.DataFrame(data=dic,index=index)
df['Stock_Price']=[var0,"-","-","-"]
print(df)

                        Oil_Price  NASDAQ_Index  Precipitation Stock_Price
Variance               129.861042  4.902779e+06       0.209567   181.71048
Covariance              80.450813 -2.164478e+04       1.064298           -
Pearsonr_correlation     0.523222 -7.244811e-01       0.172305           -
Spearmanr_correlation    0.449956 -8.122050e-01       0.222894           -


### Hypothesis Testing: Chi-Square Test

In [84]:
def Chi_Square_Stock_Price(tar1,tar2):
    thres1=1/3*(max(Combine[tar1])-min(Combine[tar1]))+min(Combine[tar1])
    thres2=2/3*(max(Combine[(tar1)])-min(Combine[tar1]))+min(Combine[tar1])
    
    stocklow = len(Combine[(Combine[tar1]<thres1)])
    stockmid = len(Combine[(Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    stockhigh = len(Combine[(Combine[tar1]>=thres2)])
    
    Thres1=1/3*(max(Combine[tar2])-min(Combine[tar2]))+min(Combine[tar2])
    Thres2=2/3*(max(Combine[tar2])-min(Combine[tar2]))+min(Combine[tar2])
    auxiliaryLow_Day=len(Combine[(Combine[tar2]<Thres1)])
    auxiliaryMid_Day=len(Combine[(Combine[tar2]<Thres2)&(Combine[tar2]>=Thres1)])
    auxiliaryHigh_Day=len(Combine[(Combine[tar2]>=Thres2)])
    
    stocklow_auxiliaryLow = len(Combine[(Combine[tar2]<Thres1)&
                         (Combine[tar1]<thres1)])
    stocklow_auxiliaryMid = len(Combine[(Combine[tar2]<Thres2)&(Combine[tar2]>=Thres1)&
                                        (Combine[tar1]<thres1)])
    stocklow_auxiliaryHigh = len(Combine[(Combine[tar2]>=Thres2)&
                          (Combine[tar1]<thres1)])
    
    stockmid_auxiliaryLow = len(Combine[(Combine[tar2]<Thres1)&
                                        (Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    stockmid_auxiliaryMid = len(Combine[(Combine[tar2]<Thres2)&(Combine[tar2]>=Thres1)&
                                        (Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    stockmid_auxiliaryHigh = len(Combine[(Combine[tar2]>=Thres2)&
                          (Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    
    stockhigh_auxiliaryLow = len(Combine[(Combine[tar2]<Thres1)&
                          (Combine[tar1]>=thres2)])
    stockhigh_auxiliaryMid = len(Combine[(Combine[tar2]<Thres2)&(Combine[tar2]>=Thres1)&
                          (Combine[tar1]>=thres2)])
    stockhigh_auxiliaryHigh = len(Combine[(Combine[tar2]>=Thres2)&
                           (Combine[tar1]>=thres2)])
    
    auxiliaryLow=[stocklow_auxiliaryLow,stockmid_auxiliaryLow,stockhigh_auxiliaryLow]  
    auxiliaryMid=[stocklow_auxiliaryMid,stockmid_auxiliaryMid,stockhigh_auxiliaryMid] 
    auxiliaryHigh=[stocklow_auxiliaryHigh,stockmid_auxiliaryHigh,stockhigh_auxiliaryHigh]                                      
                                         
    index=['stocklow','stockmid','stockhigh']
    D={'auxiliaryLow':auxiliaryLow,'auxiliaryMid':auxiliaryMid,'auxiliaryHigh':auxiliaryHigh}
    Table_Simple=pd.DataFrame(data=D,index=index,columns=None)   
    
    index=['stocklow','stockmid','stockhigh','Total']
    auxiliaryLow=[stocklow_auxiliaryLow,stockmid_auxiliaryLow,stockhigh_auxiliaryLow,auxiliaryLow_Day]  
    auxiliaryMid=[stocklow_auxiliaryMid,stockmid_auxiliaryMid,stockhigh_auxiliaryMid,auxiliaryMid_Day] 
    auxiliaryHigh=[stocklow_auxiliaryHigh,stockmid_auxiliaryHigh,stockhigh_auxiliaryHigh,auxiliaryHigh_Day]
    
    Total=[stocklow,stockmid,stockhigh,(stocklow+stockmid+stockhigh)]
    D2={'auxiliaryLow':auxiliaryLow,'auxiliaryMid':auxiliaryMid,'auxiliaryHigh':auxiliaryHigh, 'Total': Total}
    Table_with_Total = pd.DataFrame(data=D2,index=index,columns=None)
    return (Table_Simple,Table_with_Total)

In [85]:
def Chi_Sqaure(CaliTable):
    stat, p, dof, expected = chi2_contingency(CaliTable)
    print("statistic",stat)
    print("p-value",p)
    print("degres of fredom: ",dof)
    print("table of expected frequencies\n",expected)
    prob = 0.90
    critical = chi2.ppf(prob, dof)
    if abs(stat) >= critical:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')

In [86]:
OilTable, OilTable_with_Total=Chi_Square_Stock_Price('Stock_Price','Oil_Price')
Chi_Sqaure(OilTable)

statistic 214.16169905703848
p-value 3.3816346269019644e-45
degres of fredom:  4
table of expected frequencies
 [[ 24.36103152 165.21776504 137.42120344]
 [ 31.14040115 211.19579752 175.66380134]
 [ 22.49856734 152.58643744 126.91499522]]
Dependent (reject H0)


In [87]:
NASDAQTable, NASDAQTable_with_Total=Chi_Square_Stock_Price('Stock_Price','NASDAQ_Index')
Chi_Sqaure(NASDAQTable)

statistic 708.693611678762
p-value 4.568671791240487e-152
degres of fredom:  4
table of expected frequencies
 [[220.49856734  54.96848138  51.53295129]
 [281.86055396  70.26552053  65.8739255 ]
 [203.6408787   50.76599809  47.59312321]]
Dependent (reject H0)


In [88]:
PrecipitationTable, PrecipitationTable_with_Total=Chi_Square_Stock_Price('Stock_Price','Precipitation')
Chi_Sqaure(PrecipitationTable)

statistic 151.03672795427448
p-value 1.2205537749996283e-31
degres of fredom:  4
table of expected frequencies
 [[ 59.34097421 158.34670487 109.31232092]
 [ 75.8548233  202.41260745 139.73256925]
 [ 54.80420248 146.24068768 100.95510984]]
Dependent (reject H0)


In [89]:
def Chi_Square_Stock_Price_for_Pandemic(tar1,tar2):
    thres1=1/3*(max(Combine[tar1])-min(Combine[tar1]))+min(Combine[tar1])
    thres2=2/3*(max(Combine[(tar1)])-min(Combine[tar1]))+min(Combine[tar1])
    
    stocklow = len(Combine[(Combine[tar1]<thres1)])
    stockmid = len(Combine[(Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    stockhigh = len(Combine[(Combine[tar1]>=thres2)])
    
    Pandemic_Day=len(Combine[(Combine[tar2]==True)])
    NoPandemic_Day=len(Combine[(Combine[tar2]==False)])
    
    stocklow_Pandemic = len(Combine[(Combine[tar2]==True)&
                         (Combine[tar1]<thres1)])
    stocklow_NoPandemic = len(Combine[(Combine[tar2]==False)&
                                        (Combine[tar1]<thres1)])
    
    stockmid_Pandemic = len(Combine[(Combine[tar2]==True)&
                                        (Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    stockmid_NoPandemic = len(Combine[(Combine[tar2]==False)&
                                        (Combine[tar1]<thres2)&(Combine[tar1]>=thres1)])
    
    stockhigh_Pandemic = len(Combine[(Combine[tar2]==True)&
                          (Combine[tar1]>=thres2)])
    stockhigh_NoPandemic = len(Combine[(Combine[tar2]==False)&
                          (Combine[tar1]>=thres2)])
    
    Pandemic=[stocklow_Pandemic,stockmid_Pandemic,stockhigh_Pandemic]  
    NoPandemic=[stocklow_NoPandemic,stockmid_NoPandemic,stockhigh_NoPandemic] 
                                 
                                         
    index=['stocklow','stockmid','stockhigh']
    D={'Pandemic':Pandemic,'NoPandemic':NoPandemic}
    Table_Simple=pd.DataFrame(data=D,index=index,columns=None)   
    
    index=['stocklow','stockmid','stockhigh','Total']
    Pandemic=[stocklow_Pandemic,stockmid_Pandemic,stockhigh_Pandemic,Pandemic_Day]  
    NoPandemic=[stocklow_NoPandemic,stockmid_NoPandemic,stockhigh_NoPandemic,NoPandemic_Day] 
    
    Total=[stocklow,stockmid,stockhigh,(stocklow+stockmid+stockhigh)]
    D2={'Pandemic':Pandemic,'NoPandemic':NoPandemic, 'Total': Total}
    Table_with_Total = pd.DataFrame(data=D2,index=index,columns=None)
    return (Table_Simple,Table_with_Total)

In [90]:
casesTable, casesTable_with_Total=Chi_Square_Stock_Price_for_Pandemic('Stock_Price','New_cases')
Chi_Sqaure(casesTable)

statistic 876.8208713288897
p-value 3.988108655809491e-191
degres of fredom:  2
table of expected frequencies
 [[110.56160458 216.43839542]
 [141.32951289 276.67048711]
 [102.10888252 199.89111748]]
Dependent (reject H0)


# Inference

In [91]:
image_dir='./image/Inference/single'
if not os.path.exists(image_dir):
    os.makedirs(image_dir)

**Train test split and model fit**

1 Split data to train the model and test set.
2 fit the model
3 make prediction and plot

In [92]:
 def train_test_split(Data: pd.DataFrame) -> pd.DataFrame:
    data = Data.copy()
    data.reset_index(inplace=True)    
    df=data.rename(columns={'Date':'ds','Stock_Price':'y'})
    
    train = df.set_index('ds').loc[:'2021-04-30', :].reset_index()
    test = df.set_index('ds').loc['2021-05-03':, :].reset_index()
    return train,test

def fit_model(train):   
    
    m = Prophet(
        holidays=holidays_df,
#         changepoint_prior_scale=0.05, 
        seasonality_mode='multiplicative',
        daily_seasonality=False,
        yearly_seasonality=True, 
        weekly_seasonality=True, 
#        growth="logistic",
    )
    
#     m.add_seasonality(name='monthly', period=30.5, fourier_order=5, prior_scale=0.1)
#     m.add_country_holidays(country_name='US')   
    
    m.fit(train)
    return m

def make_predict(m,periods):    
    future = m.make_future_dataframe(periods=periods, freq='1D')
    future=future.loc[future['ds'].dt.weekday.isin([0, 1, 2, 3, 4])]
    forecast = m.predict(future)   
    fig = m.plot_components(forecast, figsize=(12, 16))

    return forecast,future

def make_predictions_df(forecast, data_train, data_test): 
    """
    Function to convert the output Prophet dataframe to a datetime index and append the actual target values at the end
    """
    forecast.index = pd.to_datetime(forecast.ds)
    data_train.index = pd.to_datetime(data_train.ds)
    data_test.index = pd.to_datetime(data_test.ds)
    data = pd.concat([data_train, data_test], axis=0)
    forecast.loc[:,'y'] = data.loc[:,'y']
    
    return forecast

def plot_predictions(forecast, start_date):
    """
    Function to plot the predictions 
    """
    f, ax = plt.subplots(figsize=(14, 8))
    
    train = forecast.loc[start_date:'2021-04-30',:]
    ax.plot(train.index, train.y, 'ko', markersize=3)
    ax.plot(train.index, train.yhat, color='steelblue', lw=0.5)
    ax.fill_between(train.index, train.yhat_lower, train.yhat_upper, color='steelblue', alpha=0.3)
    
    test = forecast.loc['2021-05-03':,:]
    ax.plot(test.index, test.y, 'ro', markersize=3)
    ax.plot(test.index, test.yhat, color='coral', lw=0.5)
    ax.fill_between(test.index, test.yhat_lower, test.yhat_upper, color='coral', alpha=0.3)
    ax.axvline(forecast.loc['2021-05-03', 'ds'], color='k', ls='--', alpha=0.7)
    ax.grid(ls=':', lw=0.5)
    return f, ax


In [93]:
def create_joint_plot(forecast, x='yhat', y='y', title=None): 

    g = sn.jointplot(x='yhat', y='y', data=forecast, kind="reg", color="b")
    g.fig.set_figwidth(8)
    g.fig.set_figheight(8)
    
    ax = g.fig.axes[1]
    if title is not None: 
        ax.set_title(title, fontsize=16)

    ax = g.fig.axes[0]
    ax.text(0.2, 0.8, "R = {:+4.2f}".format(forecast.loc[:,['y','yhat']].corr().iloc[0,1]), fontsize=16)
    R=forecast.loc[:,['y','yhat']].corr().iloc[0,1]
    ax.set_xlabel('Predictions', fontsize=15)
    ax.set_ylabel('Observations', fontsize=15)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.grid(ls=':')
    [l.set_fontsize(13) for l in ax.xaxis.get_ticklabels()]
    [l.set_fontsize(13) for l in ax.yaxis.get_ticklabels()];

    ax.grid(ls=':')
    return R

In [94]:
import json
from fbprophet.serialize import model_to_json, model_from_json

def save_model(filename):
    model_dir='./model'
    if not os.path.exists(model_dir):
        os.makedirs(model_dir)    
    file_path=model_dir+'/'+filename+'.json'
    with open(file_path, 'w') as fout:
        json.dump(model_to_json(m), fout)  # Save model
        
def load_model(filename):
    model_dir='./model'
    if not os.path.exists(model_dir):
        os.makedirs(model_dir)    
    file_path=model_dir+'/'+filename+'.json'
    with open(file_path, 'r') as fin:
        m = model_from_json(json.load(fin))  # Load model
    return m

1.Using only time series of stock prices

In [95]:
train,test=train_test_split(Stock_fit)
m = fit_model(train)
forecast,future=make_predict(m,30)
plt.close()
m.plot_components(forecast).savefig('./image/Inference/single/stock forecast')
plt.close()
result = make_predictions_df(forecast, train, test)
result.loc[:,'yhat'] = result.yhat.clip(lower=0)
result.loc[:,'yhat_lower'] = result.yhat_lower.clip(lower=0)
result.loc[:, 'yhat_upper'] = result.yhat_upper.clip(lower=0)
result.head()

f, ax = plot_predictions(result, '2017-04-03')
plt.savefig('./image/Inference/single/stock')
plt.close()


In [96]:
r0=create_joint_plot(result.loc[:'2021-4-30', :], title='Train set')
plt.savefig('./image/Inference/single/stock Train set')
plt.close()

In [97]:
rt0=create_joint_plot(result.loc['2021-05-03':, :], title='Test set')
plt.savefig('./image/Inference/single/stock Test set')
plt.close()

In [98]:
save_model('Single_model')

In [99]:
predict0 = pd.DataFrame({
    'True_Value':Stock_data.loc['2021-05-03':,'Stock_Price'],
    'Predict': result.loc['2021-05-03':,'yhat']
    })

In [100]:
predict0.loc[:,'Predict']=scaler0.inverse_transform(pd.DataFrame(predict0.loc['2021-05-03':,'Predict']))

In [101]:
predict0.head()

True_Value    Predict
2021-05-03   21.950001  21.934342
2021-05-04   21.420000  21.940400
2021-05-05   21.570000  21.905665
2021-05-06   21.490000  21.856712
2021-05-07   22.000000  21.833850

2.Incorporating auxiliary data

In [102]:
def Stock_with_auxiliary(data_fit,title):
    image_dir='./image/Inference/'+title
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)
    Stock_N=pd.concat([Stock_fit,data_fit],axis=1)
    train_N, test_N=train_test_split(Stock_N)

    m = Prophet(holidays=holidays_df, 
                seasonality_mode='multiplicative',
                yearly_seasonality=True, 
                weekly_seasonality=True,
                daily_seasonality=False)
    m.add_regressor(title, mode='multiplicative')
    
    m.fit(train_N)

    future = m.make_future_dataframe(periods=30, freq='1D')
    future=future.set_index('ds')
    futures = pd.concat([future, data_fit.loc[:, [title]]], axis=1)
    futures.reset_index(inplace=True)
    futures.rename(columns={'index':'ds'},inplace=True)
    futures =futures.loc[futures['ds'].dt.weekday.isin([0, 1, 2, 3, 4])]

    forecast = m.predict(futures)
    f = m.plot_components(forecast, figsize=(12, 16))
    plt.close()
    m.plot_components(forecast).savefig('./image/Inference/'+title+'/forecast')
    plt.close()
    result = make_predictions_df(forecast, train_N, test_N)
    result.loc[:,'yhat'] = result.yhat.clip(lower=0)
    result.loc[:,'yhat_lower'] = result.yhat_lower.clip(lower=0)
    result.loc[:, 'yhat_upper'] = result.yhat_upper.clip(lower=0)
    result.head()

    f, ax = plot_predictions(result, '2017-04-03')
    plt.savefig('./image/Inference/'+title+'/predict')
    plt.close()
    R_train = create_joint_plot(result.loc[:'2021-4-30', :], title='Train set')
    plt.savefig('./image/Inference/'+title+'/Train set')
    plt.close()
    R_test = create_joint_plot(result.loc['2021-05-03':, :], title='Test set')
    plt.savefig('./image/Inference/'+title+'/Test set')
    plt.close()
    save_model(title+'_model')

    predict = pd.DataFrame({
        'True_Value':Stock_data.loc['2021-05-03':,'Stock_Price'],
        'Predict': result.loc['2021-05-03':,'yhat']
        })
    predict.loc[:,'Predict']=scaler0.inverse_transform(pd.DataFrame(predict.loc['2021-05-03':,'Predict']))
    return predict,m,R_train,R_test

In [103]:
def Stock_with_auxiliary_with_Pandemic(data_fit1,title):
    image_dir='./image/Inference/with_Pandemic/'+title
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)
    data_fit2=Combine['New_cases']
    Stock_N=pd.concat([Stock_fit,data_fit1,data_fit2],axis=1)
    Stock_N=Stock_N.rename(columns={'New_cases':'Pandemic'})
    Stock_N['NoPandemic']=~data_fit2
    train_N, test_N=train_test_split(Stock_N)
  
    m = Prophet(holidays=holidays_df, 
                seasonality_mode='multiplicative',
                yearly_seasonality=True, 
                weekly_seasonality=True,
                daily_seasonality=False)
    m.add_regressor(title, mode='multiplicative')
    m.add_seasonality(name='Pandemic', period=365, fourier_order=3, mode='multiplicative', condition_name='Pandemic')
    m.add_seasonality(name='NoPandemic', period=365, fourier_order=3, mode='multiplicative', condition_name='NoPandemic')
    m.fit(train_N)
    future = m.make_future_dataframe(periods=30, freq='1D')
    future=future.set_index('ds')
    futures = pd.concat([future, data_fit1.loc[:, [title]],Stock_N['Pandemic'],Stock_N['NoPandemic']], axis=1)
    futures.reset_index(inplace=True)
    futures.rename(columns={'index':'ds'},inplace=True)
    futures =futures.loc[futures['ds'].dt.weekday.isin([0, 1, 2, 3, 4])]

    forecast = m.predict(futures)

    f = m.plot_components(forecast, figsize=(12, 16))
    plt.close()
    m.plot_components(forecast).savefig('./image/Inference/with_Pandemic/'+title+'/forecast')
    plt.close()
    result = make_predictions_df(forecast, train_N, test_N)
    result.loc[:,'yhat'] = result.yhat.clip(lower=0)
    result.loc[:,'yhat_lower'] = result.yhat_lower.clip(lower=0)
    result.loc[:, 'yhat_upper'] = result.yhat_upper.clip(lower=0)
    result.head()

    f, ax = plot_predictions(result, '2017-04-03')
    plt.savefig('./image/Inference/with_Pandemic/'+title+'/predic')
    plt.close()
    R_train=create_joint_plot(result.loc[:'2021-4-30', :], title='Train set')
    plt.savefig('./image/Inference/with_Pandemic/'+title+'/Train set')
    plt.close()
    R_test=create_joint_plot(result.loc['2021-05-03':, :], title='Test set')
    plt.savefig('./image/Inference/with_Pandemic/'+title+'/Test set')
    plt.close()
    save_model(title+'_Pandemic_model')

    predict = pd.DataFrame({
        'True_Value':Stock_data.loc['2021-05-03':,'Stock_Price'],
        'Predict': result.loc['2021-05-03':,'yhat']
        })
    predict.loc[:,'Predict']=scaler0.inverse_transform(pd.DataFrame(predict.loc['2021-05-03':,'Predict']))
    return predict,m,R_train,R_test

In [104]:
def Stock_with_all_auxiliary(title):

    image_dir='./image/Inference/'+title
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)
        
    Stock_N=pd.concat([Stock_fit,Oil_fit,NASDAQ_fit,Precip_fit],axis=1)
    train_N, test_N=train_test_split(Stock_N)
  
    m = Prophet(holidays=holidays_df, 
                seasonality_mode='multiplicative',
                yearly_seasonality=True, 
                weekly_seasonality=True,
                daily_seasonality=False)
    m.add_regressor('Oil_Price', mode='multiplicative')
    m.add_regressor('NASDAQ_Index', mode='multiplicative')
    m.add_regressor('Precipitation', mode='multiplicative')
                       
    m.fit(train_N)
    future = m.make_future_dataframe(periods=30, freq='1D')
    future=future.set_index('ds')
    futures = pd.concat([future, Oil_fit.loc[:, ['Oil_Price']],NASDAQ_fit.loc[:, ['NASDAQ_Index']],Precip_fit.loc[:, ['Precipitation']]], 
                         axis=1)
    futures.reset_index(inplace=True)
    futures.rename(columns={'index':'ds'},inplace=True)
    futures =futures.loc[futures['ds'].dt.weekday.isin([0, 1, 2, 3, 4])]

    forecast = m.predict(futures)

    f = m.plot_components(forecast, figsize=(12, 16))
    plt.close()
    m.plot_components(forecast).savefig('./image/Inference/'+title+'/forecast')
    plt.close()
    result = make_predictions_df(forecast, train_N, test_N)
    result.loc[:,'yhat'] = result.yhat.clip(lower=0)
    result.loc[:,'yhat_lower'] = result.yhat_lower.clip(lower=0)
    result.loc[:, 'yhat_upper'] = result.yhat_upper.clip(lower=0)
    result.head()

    f, ax = plot_predictions(result, '2017-04-03')
    plt.savefig('./image/Inference/'+title+'/predic')
    plt.close()
    R_train=create_joint_plot(result.loc[:'2021-4-30', :], title='Train set')
    plt.savefig('./image/Inference/'+title+'/Train set')
    plt.close()
    R_test=create_joint_plot(result.loc['2021-05-03':, :], title='Test set')
    plt.savefig('./image/Inference/'+title+'/Test set')
    plt.close()
    save_model(title+'_model')

    predict = pd.DataFrame({
        'True_Value':Stock_data.loc['2021-05-03':,'Stock_Price'],
        'Predict': result.loc['2021-05-03':,'yhat']
        })
    predict.loc[:,'Predict']=scaler0.inverse_transform(pd.DataFrame(predict.loc['2021-05-03':,'Predict']))
    return predict,m,R_train,R_test

In [105]:
def Stock_with_all_auxiliary_with_Pandemic(title):

    image_dir='./image/Inference/'+title
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)
    
    data_fit=Combine['New_cases']
    Stock_N=pd.concat([Stock_fit,Oil_fit,NASDAQ_fit,Precip_fit,data_fit],axis=1)
    Stock_N=Stock_N.rename(columns={'New_cases':'Pandemic'})
    Stock_N['NoPandemic']=~data_fit
    train_N, test_N=train_test_split(Stock_N)
  
    m = Prophet(holidays=holidays_df, 
                seasonality_mode='multiplicative',
                yearly_seasonality=True, 
                weekly_seasonality=True,
                daily_seasonality=False)
    m.add_regressor('Oil_Price', mode='multiplicative')
    m.add_regressor('NASDAQ_Index', mode='multiplicative')
    m.add_regressor('Precipitation', mode='multiplicative')
    m.add_seasonality(name='Pandemic', period=365, fourier_order=3, mode='multiplicative', condition_name='Pandemic')
    m.add_seasonality(name='NoPandemic', period=365, fourier_order=3, mode='multiplicative', condition_name='NoPandemic')
    m.fit(train_N)
    future = m.make_future_dataframe(periods=30, freq='1D')
    future=future.set_index('ds')
    futures = pd.concat([future, Oil_fit.loc[:, ['Oil_Price']],NASDAQ_fit.loc[:, ['NASDAQ_Index']],Precip_fit.loc[:, ['Precipitation']],
                         Stock_N['Pandemic'],Stock_N['NoPandemic']], axis=1)
    futures.reset_index(inplace=True)
    futures.rename(columns={'index':'ds'},inplace=True)
    futures =futures.loc[futures['ds'].dt.weekday.isin([0, 1, 2, 3, 4])]

    forecast = m.predict(futures)

    f = m.plot_components(forecast, figsize=(12, 16))
    plt.close()
    m.plot_components(forecast).savefig('./image/Inference/'+title+'/forecast')
    plt.close()
    result = make_predictions_df(forecast, train_N, test_N)
    result.loc[:,'yhat'] = result.yhat.clip(lower=0)
    result.loc[:,'yhat_lower'] = result.yhat_lower.clip(lower=0)
    result.loc[:, 'yhat_upper'] = result.yhat_upper.clip(lower=0)
    result.head()

    f, ax = plot_predictions(result, '2017-04-03')
    plt.savefig('./image/Inference/'+title+'/predic')
    plt.close()
    R_train=create_joint_plot(result.loc[:'2021-4-30', :], title='Train set')
    plt.savefig('./image/Inference/'+title+'/Train set')
    plt.close()
    R_test=create_joint_plot(result.loc['2021-05-03':, :], title='Test set')
    plt.savefig('./image/Inference/'+title+'/Test set')
    plt.close()
    save_model(title+'_Pandemic_model')

    predict = pd.DataFrame({
        'True_Value':Stock_data.loc['2021-05-03':,'Stock_Price'],
        'Predict': result.loc['2021-05-03':,'yhat']
        })
    predict.loc[:,'Predict']=scaler0.inverse_transform(pd.DataFrame(predict.loc['2021-05-03':,'Predict']))
    return predict,m,R_train,R_test

In [106]:
predict1,m1,r1,rt1=Stock_with_auxiliary(Oil_fit,'Oil_Price')
Predict1,M1,R1,RT1=Stock_with_auxiliary_with_Pandemic(Oil_fit,'Oil_Price')

In [107]:
predict2,m2,r2,rt2=Stock_with_auxiliary(NASDAQ_fit,'NASDAQ_Index')
Predict2,M2,R2,RT2=Stock_with_auxiliary_with_Pandemic(NASDAQ_fit,'NASDAQ_Index')

In [108]:
predict3,m3,r3,rt3=Stock_with_auxiliary(Precip_fit,'Precipitation')
Predict3,M3,R3,RT3=Stock_with_auxiliary_with_Pandemic(Precip_fit,'Precipitation')

In [109]:
predictA,mA,rA,rtA=Stock_with_all_auxiliary("All")
PredictA,MA,RA,RTA=Stock_with_all_auxiliary_with_Pandemic("All_with_Pandemic")

Evaluate the performance

In [110]:
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score
def MSE(predict):
    mse=mean_squared_error(predict['True_Value'],predict['Predict'])
    return mse

In [111]:
from sklearn.metrics import r2_score
def R_sqaure(predict):
    return r2_score(predict['True_Value'],predict['Predict'])


In [112]:
index=['stock','with Oil','with NASDAQ','with Precipitation','All','with Oil_PAN','with NASDAQ_PAN','with Precipitation_PAN','All_PAN']
correlation_train=[r0,r1,r2,r3,rA,R1,R2,R3,RA]
correlation_test=[rt0,rt1,rt2,rt3,rtA,RT1,RT2,RT3,RTA]
MSE_result=[MSE(predict0),MSE(predict1),MSE(predict2),MSE(predict3),MSE(predictA),
            MSE(Predict1),MSE(Predict2),MSE(Predict3),MSE(PredictA)]
R_sqaure_result=[R_sqaure(predict0),R_sqaure(predict1),R_sqaure(predict2),R_sqaure(predict3),R_sqaure(predictA),
                 R_sqaure(Predict1),R_sqaure(Predict2),R_sqaure(Predict3),R_sqaure(PredictA)]
Result_table={'correlation_train':correlation_train,'correlation_test':correlation_test,'MSE_result':MSE_result,'R_sqaure_result':R_sqaure_result}

In [113]:
Df=pd.DataFrame(Result_table,index=index)

In [114]:
Df

correlation_train  correlation_test  MSE_result  \
stock                            0.991097          0.688185    1.246649   
with Oil                         0.990913          0.691466    1.440858   
with NASDAQ                      0.991928          0.810072    0.821112   
with Precipitation               0.990998          0.709175    1.468950   
All                              0.991777          0.802347    1.128327   
with Oil_PAN                     0.990786         -0.767049    4.534020   
with NASDAQ_PAN                  0.992023          0.877136    4.048300   
with Precipitation_PAN           0.990759         -0.799793    5.132313   
All_PAN                          0.993116         -0.518806    5.449349   

                        R_sqaure_result  
stock                         -0.189704  
with Oil                      -0.375042  
with NASDAQ                    0.216395  
with Precipitation            -0.401851  
All                           -0.076787  
with Oil_PAN                  -3.326913  
with NASDAQ_PAN               -2.863381  
with Precipitation_PAN        -3.897878  
All_PAN                       -4.200432

In [122]:
Predict_table=predict0.copy()
Predict_table['N_predict']=predict2['Predict']
Predict_table['N_predict_PAN']=Predict2['Predict']

In [123]:
Predict_table

True_Value    Predict  N_predict  N_predict_PAN
2021-05-03   21.950001  21.934342  22.077118      19.678055
2021-05-04   21.420000  21.940400  21.785593      19.262819
2021-05-05   21.570000  21.905665  21.743741      19.220425
2021-05-06   21.490000  21.856712  21.816173      19.353246
2021-05-07   22.000000  21.833850  21.969279      19.613476
2021-05-10   22.000000  21.776751  21.633950      19.288033
2021-05-11   21.570000  21.800617  21.644801      19.378144
2021-05-12   20.760000  21.785726  21.244461      18.881194
2021-05-13   21.209999  21.758907  21.379690      19.176620
2021-05-14   22.400000  21.760881  21.769614      19.856249
2021-05-17   23.350000  21.788974  21.824836      20.327697
2021-05-18   23.559999  21.844094  21.770018      20.400827
2021-05-19   22.969999  21.860156  21.804680      20.619278
2021-05-20   22.600000  21.863902  22.126573      21.271446
2021-05-21   22.570000  21.896160  22.078671      21.394235
2021-05-24   22.990000  22.005575  22.447529      22.580166
2021-05-25   23.209999  22.083453  22.482523      22.870744
2021-05-26   23.900000  22.118311  22.623621      23.332206
2021-05-27   24.430000  22.136885  22.654435      23.643856
2021-05-28   24.240000  22.180271  22.698734      23.988235